name: the_weather_app
description: "A new Flutter project."
publish_to: 'none' # Remove this line if you wish to publish to pub.dev
version: 1.0.0+1

environment:
  sdk: ">=3.3.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  intl: ^0.20.2

  # State management
  flutter_riverpod: ^2.5.1
  riverpod_annotation: ^2.3.5

  # Networking & JSON
  dio: ^5.7.0
  json_annotation: ^4.9.0

  # Codegen & Models
  freezed_annotation: ^2.4.1

  # Routing
  go_router: ^14.2.0

  # Storage (lưu placeId, geocode)
  shared_preferences: ^2.3.2

  # UI
  google_fonts: ^6.2.1
  material_symbols_icons: ^4.2767.0 # đảm bảo icon tồn tại trong libs
  flutter_svg: ^2.0.10+1

dev_dependencies:
  build_runner: ^2.4.11
  freezed: ^2.5.7
  json_serializable: ^6.9.0
  riverpod_generator: ^2.4.0
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
  generate: true  # bật gen-l10n
